// generated by gemini 3

import type { Aircraft } from './types/Aircraft';
import type { CommercialFlight } from './types/CommercialFlight';
import type { CrewMember } from './types/CrewMember';
import type { FlightCrew } from './types/FlightCrew';

// --- Dummy Data Stores ---

let aircrafts: Aircraft[] = [
  { aircraftId: "A-101", aircraftType: "GBR-10", maxCapacity: 45, currentLocation: "Lincoln" },
  { aircraftId: "A-102", aircraftType: "NU-150", maxCapacity: 75, currentLocation: "Evanston" },
  { aircraftId: "A-103", aircraftType: "GBR-10", maxCapacity: 45, currentLocation: "Iowa City" },
];

let crewMembers: CrewMember[] = [
  { crewMemberId: "C-001", name: "John Doe", role: "Captain", location: "Lincoln" },
  { crewMemberId: "C-002", name: "Jane Smith", role: "First Officer", location: "Evanston" },
  { crewMemberId: "C-003", name: "Bob Johnson", role: "Flight Attendant", location: "Lincoln" },
];

let flights: CommercialFlight[] = [
  { 
    flightGuid: "F-500", 
    aircraftId: "A-101", 
    origin: "Lincoln", 
    destination: "Evanston", 
    estTouchdown: null, actTouchdown: null, schedTouchdown: null,
    estTakeoff: null, actTakeoff: null, schedTakeoff: "2025-10-15T08:00:00"
  },
  { 
    flightGuid: "F-501", 
    aircraftId: "A-102", 
    origin: "Evanston", 
    destination: "West Lafayette", 
    estTouchdown: null, actTouchdown: null, schedTouchdown: null,
    estTakeoff: null, actTakeoff: null, schedTakeoff: "2025-10-15T14:30:00"
  },
];

let flightCrews: FlightCrew[] = [];

// --- Helper to simulate network delay ---
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// --- Mock Services ---

export const aircraftService = {
  getAircrafts: async () => {
    await delay(500);
    return { data: [...aircrafts] };
  },
  getAircraftById: async (id: string) => {
    await delay(300);
    return { data: aircrafts.find(a => a.aircraftId === id) };
  },
  updateAircraft: async (id: string, data: Aircraft) => {
    await delay(500);
    aircrafts = aircrafts.map(a => (a.aircraftId === id ? data : a));
    return { data };
  },
  createAircraft: async (data: Aircraft) => {
    await delay(500);
    aircrafts.push(data);
    return { data };
  },
  deleteAircraft: async (id: string) => {
    await delay(500);
    aircrafts = aircrafts.filter(a => a.aircraftId !== id);
    return { data: { success: true } };
  },
};

export const commercialFlightService = {
  getCommercialFlights: async () => {
    await delay(500);
    return { data: [...flights] };
  },
  getCommercialFlightById: async (id: string) => {
    await delay(300);
    return { data: flights.find(f => f.flightGuid === id) };
  },
  updateCommercialFlight: async (id: string, data: CommercialFlight) => {
    await delay(500);
    flights = flights.map(f => (f.flightGuid === id ? data : f));
    return { data };
  },
  createCommercialFlight: async (data: CommercialFlight) => {
    await delay(500);
    flights.push(data);
    return { data };
  },
  deleteCommercialFlight: async (id: string) => {
    await delay(500);
    flights = flights.filter(f => f.flightGuid !== id);
    return { data: { success: true } };
  },
};

export const crewMemberService = {
  getCrewMembers: async () => {
    await delay(500);
    return { data: [...crewMembers] };
  },
  getCrewMemberById: async (id: string) => {
    await delay(300);
    return { data: crewMembers.find(c => c.crewMemberId === id) };
  },
  updateCrewMember: async (id: string, data: CrewMember) => {
    await delay(500);
    crewMembers = crewMembers.map(c => (c.crewMemberId === id ? data : c));
    return { data };
  },
  createCrewMember: async (data: CrewMember) => {
    await delay(500);
    crewMembers.push(data);
    return { data };
  },
  deleteCrewMember: async (id: string) => {
    await delay(500);
    crewMembers = crewMembers.filter(c => c.crewMemberId !== id);
    return { data: { success: true } };
  },
};

export const flightCrewService = {
  getFlightCrews: async () => {
    await delay(500);
    return { data: [...flightCrews] };
  },
  getFlightCrewById: async (id: string) => {
    await delay(300);
    return { data: flightCrews.find(fc => fc.flightId === id) }; // Simplified lookup
  },
  updateFlightCrew: async (id: string, data: FlightCrew) => {
    await delay(500);
    // Note: Mocking update on composite keys or complex relationships is tricky, 
    // but for simple lists this is fine.
    return { data };
  },
  createFlightCrew: async (data: FlightCrew) => {
    await delay(500);
    flightCrews.push(data);
    return { data };
  },
  deleteFlightCrew: async (id: string) => {
    await delay(500);
    // Logic for deleting relation would go here
    return { data: { success: true } };
  },
};

export default {
  aircraftService,
  commercialFlightService,
  crewMemberService,
  flightCrewService
};