// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Model.Database;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AirlineDbContext))]
    [Migration("20251209165410_AddUpdateRecords")]
    partial class AddUpdateRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Model.Aircraft.Aircraft", b =>
                {
                    b.Property<Guid>("AircraftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("AircraftID");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Server.Model.Crew_Member.CrewMember", b =>
                {
                    b.Property<Guid>("CrewMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrewMemberId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("Server.Model.Flight.CommercialFlight", b =>
                {
                    b.Property<Guid>("FlightGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActTakeoff")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActTouchdown")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstTakeoff")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstTouchdown")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SchedTakeoff")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SchedTouchdown")
                        .HasColumnType("datetime2");

                    b.HasKey("FlightGuid");

                    b.HasIndex("AircraftId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Server.Model.Flight_Crew.FlightCrew", b =>
                {
                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleOnFlight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("FlightCrew");
                });

            modelBuilder.Entity("Server.Model.Update.UpdateRecord", b =>
                {
                    b.Property<Guid>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateId");

                    b.ToTable("UpdateRecords");
                });

            modelBuilder.Entity("Server.Model.Flight.CommercialFlight", b =>
                {
                    b.HasOne("Server.Model.Aircraft.Aircraft", "Plane")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("Server.Model.Flight_Crew.FlightCrew", b =>
                {
                    b.HasOne("Server.Model.Crew_Member.CrewMember", "CrewMember")
                        .WithMany("JobHistory")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Model.Flight.CommercialFlight", "Flight")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Server.Model.Aircraft.Aircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Server.Model.Crew_Member.CrewMember", b =>
                {
                    b.Navigation("JobHistory");
                });

            modelBuilder.Entity("Server.Model.Flight.CommercialFlight", b =>
                {
                    b.Navigation("CrewAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
